name: End-to-end tests, Component tests, eslint check

on: [push,pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Run Component tests ğŸ§ª
        uses: actions/checkout@v2
      - name: Run Component tests ğŸ§ª
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          browser: chrome
          install: false
          component: true
  lint:
  - name: Run Eslint checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: npm run lint
